version: "3"
services:
  statping:
    container_name: statping
    image: dockurr/statping:latest
    ports:
        - 8080:8080
    volumes:
      - /opt/statping:/app
    restart: always
    stop_grace_period: 1m
